# Full Reconstruction Configuration
# This configuration shows all available reconstruction products

plot_config:
  input_files:
    - path: /path/to/your/dlmerged_file.root
      tick_direction: TickForwards
  
  entry: 0
  
  output:
    html_file: full_reconstruction.html
    save_images: true
    image_format: png
    image_dir: ./full_reco_plots/
  
  plots:
    # MC Truth
    - name: "MC Truth"
      type: "MCTruth"
      enabled: true
      options:
        show_mctrack: true
        show_mcshower: true
        show_neutrino_vertex: true
    
    # Reconstructed neutrino
    - name: "Reco Neutrino"
      type: "RecoNu"
      enabled: true
      options:
        show_vertex: true
        show_tracks: true
        show_showers: true
    
    # CRT information
    - name: "CRT"
      type: "CRT"
      enabled: true
      options:
        show_hits: true
        show_tracks: true
        hit_size: 5
    
    # Optical flashes
    - name: "Optical Flashes"
      type: "IntimeFlash"
      enabled: true
      options:
        show_flashes: true
        flash_threshold: 10.0
    
    # LArFlow hits
    - name: "LArFlow Hits"
      type: "LArFlowHits"
      enabled: true
      options:
        show_all_hits: false
        color_by: "cluster_id"
        score_threshold: 0.5
    
    # Neutrino input clusters
    - name: "Nu Clusters"
      type: "NuInputClusters"
      enabled: true
      options:
        show_by_cluster: true
        show_by_ssnet: false
  
  viewer_3d:
    camera:
      eye:
        x: 2.0
        y: 1.5
        z: 1.0
      center:
        x: 0
        y: 0
        z: 0
    
    layout:
      width: 1600
      height: 1000
      title: "Full Event Reconstruction"
      showlegend: true
      paper_bgcolor: 'white'
    
    show_detector: true
    detector_opacity: 0.03
  
  viewer_2d:
    enabled: true
    planes:
      - plane: 0
        show: true
      - plane: 1
        show: true
      - plane: 2
        show: true
    colorscale: 'Viridis'
    contrast_range: [-30, 100]